name: build

env:
  CONAN_UPLOAD: "https://conan.yobasoft.de"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan conan_package_tools
            conan remote add conan-burrito ${{ env.CONAN_UPLOAD }}
            conan user -p ${{ env.CONAN_PASSWORD }} -r conan-burrito ${{ env.CONAN_LOGIN_USERNAME }}

      - name: Build native
        run:  python ${{ github.workspace }}/.ci/build-native.py
      - name: Native artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-${{ matrix.os }}
          path: _build/bin/

      - name: Build for Android
        run:  python .ci/build-android.py
      - name: Android artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-${{ matrix.os }}
          path: android/app/build/outputs/apk/

      - name: Build for iOS
        if: startsWith(matrix.os, 'macos')
        run:  |
          python .ci/build-ios.py
      - name: iOS artifact
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v2
        with:
          name: ios-${{ matrix.os }}
          path: _build/bin/
