name: build

env:
  CONAN_UPLOAD: "https://conan.yobasoft.de"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"

on:
  push:
    branches:
      - "*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan
            conan remote add conan-burrito ${{ env.CONAN_UPLOAD }}
            conan user -p ${{ env.CONAN_PASSWORD }} -r conan-burrito ${{ env.CONAN_LOGIN_USERNAME }}
      - name: Build native
        run:  python ${{ github.workspace }}/.ci/build-native.py
      - uses: actions/upload-artifact@v2
        with:
          name: native-windows
          path: _build/bin/

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan
            conan remote add conan-burrito ${{ env.CONAN_UPLOAD }}
            conan user -p ${{ env.CONAN_PASSWORD }} -r conan-burrito ${{ env.CONAN_LOGIN_USERNAME }}
      - name: Build native
        run:  python ${{ github.workspace }}/.ci/build-native.py
      - uses: actions/upload-artifact@v2
        with:
          name: native-macos
          path: _build/bin/
      - name: Get Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Setup requirements
        run: |
          sdkmanager --list
          sdkmanager "ndk-bundle"
          sdkmanager "platform-tools"
          sdkmanager "cmake;3.10.2.4988404"
          sdkmanager "platforms;android-29"
      - name: Build for Android
        run:  python .ci/build-android.py
      - name: Android artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-macos
          path: android/app/build/outputs/apk/
      - name: Build for iOS
        run:  |
          python .ci/build-ios.py
      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: _build/bin/

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan
            conan remote add conan-burrito ${{ env.CONAN_UPLOAD }}
            conan user -p ${{ env.CONAN_PASSWORD }} -r conan-burrito ${{ env.CONAN_LOGIN_USERNAME }}
      - name: Build native
        run:  python ${{ github.workspace }}/.ci/build-native.py
      - uses: actions/upload-artifact@v2
        with:
          name: native-ubuntu
          path: _build/bin/

